# Generated by Django 4.2.5 on 2023-09-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Служебка', 'verbose_name_plural': 'Служебки'},
        ),
        migrations.AlterField(
            model_name='task',
            name='changed',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение'),
        ),
        migrations.AlterField(
            model_name='task',
            name='closed',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Закрыта'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(verbose_name='Рассмотреть до'),
        ),
    ]
